version: '2.0'
services:
    web:
        build: ./web
        restart: always
        networks:
            - front
    api:
        build: ./api
        restart: always
        networks:
            - front
            - back
        links:
            - redis
    redis:
        image: brandonroyal/demo_redis:latest
        restart: always
        networks:
            - back
    nginx:
        image: brandonroyal/demo_nginx:latest
        restart: always
        networks: 
            - front
        links:
            - web
            - api
        ports:
            - "80:80"

networks:
    front:
        driver: bridge
    back:
        driver: bridge