version: '2.0'
services:
    web:
        build:
            context: ./web
            dockerfile: ./linux/Dockerfile
        networks:
            - front
        volumes:
            - ./web/bin:/app/bin
            - ./web/Views:/app/Views
            - ./web/wwwroot:/app/wwwroot

    api:
        build:
            context: ./api
            dockerfile: ./linux/Dockerfile
        networks:
            - front
            - back
        links:
            - redis
        volumes:
            - ./api/bin:/app/bin

    redis:
        image: redis:latest
        networks:
            - back

    nginx:
        image: nginx:latest
        networks: 
            - front
        links:
            - web
            - api
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
        ports:
            - "80:80"

networks:
    front:
        driver: bridge
    back:
        driver: bridge