version: '2.0'
services:
    web:
        build: ./web
    api:
        build: ./api
        links:
            - redis
    redis:
        image: brandonroyal/demo_redis:latest
    nginx:
        image: brandonroyal/demo_nginx:latest
        links:
            - web
            - api
        ports:
            - "80:80"