version: '2.0'
services:
    web:
        image: brandonroyal/demo_web:latest
    api:
        image: brandonroyal/demo_api:latest
        links:
            - redis
    redis:
        image: brandonroyal/demo_redis:latest
    nginx:
        image: brandonroyal/demo_nginx:latest
        links:
            - web
            - api
        ports:
            - "80:80"

networks:
    default:
        external:
            name: nat