version: '2.0'
services:
    web:
        image: brandonroyal/demo_web:latest
        networks:
            - default
    api:
        image: brandonroyal/demo_api:latest
        networks:
            - default
        links:
            - redis
    redis:
        image: brandonroyal/demo_redis:latest
        networks:
            - default
    nginx:
        image: brandonroyal/demo_nginx:latest
        networks: 
            - default
        links:
            - web
            - api
        ports:
            - "80:80"

networks:
    default:
        external:
            name: nat