version: '2.0'
services:
    web:
        build:
            context: ./web
            dockerfile: ./debug/Dockerfile
        restart: always
        networks:
            - front
    api:
        build:
            context: ./api
            dockerfile: ./debug/Dockerfile
        restart: always
        networks:
            - front
            - back
        links:
            - redis
    redis:
        image: redis:latest
        restart: always
        networks:
            - back
    proxy:
        image: nginx:latest
        restart: always
        networks: 
            - front
        links:
            - web
            - api
        volumes:
            - "./proxy/nginx.conf:/etc/nginx/nginx.conf"
        ports:
            - "80:80"

networks:
    front:
        driver: bridge
    back:
        driver: bridge