version: '2.0'
services:
    web:
        build: ./web
        restart: always
        networks:
            - front
    api:
        build: ./api
        restart: always
        networks:
            - front
            - back
        links:
            - redis
    redis:
        image: microsoft/sample-redis:windowsservercore-10.0.14300.1030
        restart: always
        networks:
            - back
    proxy:
        image: microsoft/sample-nginx:windowsservercore-10.0.14300.1030
        restart: always
        networks: 
            - front
        links:
            - web
            - api
        ports:
            - "80:80"

networks:
    front:
        driver: bridge
    back:
        driver: bridge